### ISSUE TITLE
admin cannot buy from creative shop

### ISSUE THREAD

**Issue by nephatrine** [ExcessiveAmountsOfZombies/shoppy#10]
I go into creative and spawn a creative shop block to set it up to sell things. Unfortunately when I go back to survival to actually play, I am unable to use the shop block to purchase anything. I guess it still thinks I own it so every interaction just seems to be for configuring it still? We do not have this issue with the vending blocks from Eric's Retail which easily allow purchase of items from both your own and from creative vendors.

In general, a way to purchase items from your own shop blocks would be greatly appreciated (it's basically impossible to just test the basic mod functionality in singleplayer using Shoppy) - but definitely need some way to for the creative ones as I don't suspect most admins switch to a whole different minecraft account to actually play on their servers.

**Comment by ExcessiveAmountsOfZombies** [comment]
there is a way! use /shoppy npc_shop <x> <y> <z> to fix your issue. you can use /shoppy admin_shop if you want to make it yours again.

**Comment by nephatrine** [comment]
Perfect!
