### ISSUE TITLE
Profits vanish from the bartering station after server restart

### ISSUE THREAD

**Issue by Flyvee** [ExcessiveAmountsOfZombies/shoppy#13]
If any items is traded with a bartering block and the server restarts, then the 'profits' in the bartering block is cleared and the block says that no profit is there or of any transactions done.

**Comment by ExcessiveAmountsOfZombies** [comment]
as in,.. immediately after bartering? or some longer period of time after?

**Comment by Flyvee** [comment]
I mean after bartering, the profits is still there and can be taken with the shop owner, but if the server is restarted while there is still profits inside the bartering block, then once the server has finished starting back up, the profits are gone.

**Comment by ExcessiveAmountsOfZombies** [comment]
I'll have a fix in 1.0.6
