### ISSUE TITLE
No numbers recognized as valid when using chat to set shop price.

### ISSUE THREAD

**Issue by Vitalcord** [ExcessiveAmountsOfZombies/shoppy#14]
After being prompted to enter a number to update the price of the store in chat, the result will always be "You did not enter a valid number to update your shops pricing." This occurs even if the player enters only a number in chat, such as the number 1. This was not always the case, as previously the players were able to set shop prices without issue, and some shops on the server have prices.

We are using EightsEconomy, and even admins with OP 4 have this result when trying to set a price.

**Comment by ExcessiveAmountsOfZombies** [comment]
This might be fixed in 1.0.6, but in addition to that there is now an extra error message that will display which characters in a message caused the shop update to fail.
