### ISSUE TITLE
(1.0.3 1.19.2)java.lang.NoSuchFieldError: EMPTY Error

### ISSUE THREAD

**Issue by Hextaku** [ExcessiveAmountsOfZombies/shoppy#5]
Game crashes on startup with an java.lang.NoSuchFieldError: EMPTY Error.

Stacktrace is: com.epherical.shoppy.ShoppyMod.<clinit>(ShoppyMod.java:34) ~[Shoppy-1.19.2-FORGE-1.0.3-all.jar%23153!/:1.0.3] {re:classloading}

For more details, view: https://pastebin.com/4E8nmNaP

**Comment by ExcessiveAmountsOfZombies** [comment]
uploading the fix, should've taken a closer look at the jar when the build task was being weird.
