### ISSUE TITLE
i cant seem to craft the item

### ISSUE THREAD

**Issue by konspat** [ExcessiveAmountsOfZombies/shoppy#6]

**Comment by konspat** [comment]
i jsut checked with jei (just enough items) and the recipe  is nto craftable at all

**Comment by Landon-9999** [comment]
@konspat What version of Shoppy are you using? I think this problem was fixed in most recent version on CurseForge

**Comment by konspat** [comment]
version 1.03 should i try 1.04?

**Comment by Landon-9999** [comment]
Yup

**Comment by konspat** [comment]
Im using the 1.19.2 1.0.3 of shoppy and the 1.19.2 43.1.2 of forge  Sent from Mail for Windows From: Landon-9999Sent: Friday, August 26, 2022 2:29 PMTo: ExcessiveAmountsOfZombies/shoppyCc: konspat; MentionSubject: Re: [ExcessiveAmountsOfZombies/shoppy] i cant seem to craft the item (Issue ***@***.*** What version of Shoppy are you using? I think this problem was fixed in most recent version on CurseForge—Reply to this email directly, view it on GitHub, or unsubscribe.You are receiving this because you were mentioned.Message ID: ***@***.***>
