### ISSUE TITLE
[FORGE 1.0.4-all] Missing mandatory dependencies: octo_economy_api

### ISSUE THREAD

**Issue by Pingu-Pox** [ExcessiveAmountsOfZombies/shoppy#7]
**Describe the bug**
Can't start the game up with the forge version of Shoppy, says I am missing a required dependency "octo_economy_api". I tried adding the optional dependency "EightsEconomyP", but didn't help either.

**To Reproduce**
1. Install mods
2. Launch game
3. Crash
4. See error log: https://paste.ee/p/S7ygr

**Expected behavior**
Should launch just fine

**Versions:**
Forge 40.1.74
Shoppy-1.18.2-FORGE-1.0.3-all
EightsEconomyP-1.18.2-FORGE-1.0.4-all
LuckPerms-Forge-5.4.25

**Additional context**
Tested with no mods, and in a custom modpack. No change.

EDIT: Tried finding a mod called octo_economy_api on curseforge, didn't seem to find one.

**Comment by ExcessiveAmountsOfZombies** [comment]
that looks like a fabric crash log...

**Comment by ExcessiveAmountsOfZombies** [comment]
oh it's not, i think i know what's wrong i'll have a fix out soon

**Comment by ExcessiveAmountsOfZombies** [comment]
fix is being uploaded to CF right now

**Comment by Pingu-Pox** [comment]
Is the fix coming out for forge too?

**Comment by ExcessiveAmountsOfZombies** [comment]
that's what i uploaded https://www.curseforge.com/minecraft/mc-mods/shoppy/files/3981503

**Comment by Pingu-Pox** [comment]
I am so sorry! Mistook this for ticket I have open for Professions xD I will see if the issue with Shoppy is fixed!

**Comment by Pingu-Pox** [comment]
Looks good! TY!
